//! # accord-proto
//!
//! Generated gRPC + protobuf code, shared verbatim by `accord-server` and
//! `accord-client`. Keeping the wire protocol in one crate means the two sides
//! can never drift out of sync - the protobuf schema is the single source of
//! truth (see ARCHITECTURE.md section 7).
//!
//! All types below are generated at build time from `proto/*.proto` (package
//! `accord`) by the [`build.rs`](../build.rs) script. The generated items are
//! brought into this crate's root namespace, so downstream code refers to, e.g.:
//!
//! ```ignore
//! use accord_proto::auth_service_server::{AuthService, AuthServiceServer};
//! use accord_proto::messaging_service_client::MessagingServiceClient;
//! use accord_proto::{LoginRequest, ServerMessage};
//! ```
//!
//! Service module naming (generated by tonic):
//! * `*_service_server` - the trait you implement on the server.
//! * `*_service_client` - the client stub you call from the client.

// Pull in everything generated for the `accord` protobuf package. This expands
// to the contents of `$OUT_DIR/accord.rs`.
tonic::include_proto!("accord");
